In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv('/Users/pulkith/Downloads/patients.csv')
df2 = pd.read_csv('/Users/pulkith/Downloads/mebb.csv')

In [10]:
dfm = pd.merge(df1, df2, on='subject_id', how='inner')
dfm

,subject_id,gender,anchor_age,anchor_year,anchor_year_group,dod,microevent_id,hadm_id,micro_specimen_id,order_provider_id,...,org_name,isolate_num,quantity,ab_itemid,ab_name,dilution_text,dilution_comparison,dilution_value,interpretation,comments
0,10000032,F,52,2180,2014 - 2016,2180-09-09,1,NaN,636109,P28Z0X,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NEGATIVE FOR TOXOPLASMA IgG ANTIBODY BY EIA. ...
1,10000032,F,52,2180,2014 - 2016,2180-09-09,2,NaN,1836584,P28Z0X,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POSITIVE BY EIA. A positive IgG result genera...
2,10000032,F,52,2180,2014 - 2016,2180-09-09,3,NaN,4131591,P28Z0X,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,___
3,10000032,F,52,2180,2014 - 2016,2180-09-09,4,NaN,4131591,P28Z0X,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NEGATIVE FOR CMV IgM ANTIBODY BY EIA. INTERPR...
4,10000032,F,52,2180,2014 - 2016,2180-09-09,5,NaN,6028147,P28Z0X,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POSITIVE BY EIA.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,10004733,M,51,2174,2014 - 2016,NaN,1995,27411876.0,2751783,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO GROWTH.
1995,10004733,M,51,2174,2014 - 2016,NaN,1996,27411876.0,4069413,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO GROWTH.
1996,10004733,M,51,2174,2014 - 2016,NaN,1997,27411876.0,5036833,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO GROWTH.
1997,10004733,M,51,2174,2014 - 2016,NaN,1998,27411876.0,6051598,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO GROWTH.
1998,10004749,F,32,2127,2011 - 2013,NaN,1999,28691602.0,8397114,NaN,...,CLOSTRIDIUM DIFFICILE,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,___

In [11]:
dfm.to_csv('../../public/patient_store.csv', index=False)